# Generated by Django 4.1.2 on 2022-11-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_coursefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.CharField(default='no_image.svg', max_length=25, verbose_name='Cover'),
        ),
    ]
