# Generated by Django 4.1.2 on 2022-11-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_course_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.CharField(default='no_image.png', max_length=25, verbose_name='Cover'),
        ),
    ]
